name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened]

env:
 CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Create env file
        run: echo 'TOKEN_SECRET="ef822fd62938e92155fe87ef65220960c31d519f71d1b78e63f89090adde1b12caf370a1b03ee589b216ff4914d6f2a3fe5f9c84425c7b860b56e396c7292edc"' > .env
      - run: npm install
      - run: CI=true npm run test-ci
